[workspace]
members = [
  "src/noir/bin/compare/age/standard",
  "src/noir/bin/inclusion-check/nationality/standard",
  "src/noir/bin/exclusion-check/nationality/standard",
  "src/noir/bin/inclusion-check/place-of-birth/standard",
  "src/noir/bin/exclusion-check/place-of-birth/standard",
  "src/noir/bin/disclose/bytes/standard",
  "src/noir/bin/bind/standard",
  "src/noir/bin/signup-verify/rsa",
  "src/noir/bin/signup-verify/ecdsa",
  "src/noir/bin/signup-verify/fast",
  "src/noir/lib/utils",
  "src/noir/lib/commitment/common",
  "src/noir/lib/commitment/scoped-nullifier",
  "src/noir/lib/commitment/dsc-to-id",
  "src/noir/lib/commitment/integrity-to-disclosure",
  "src/noir/lib/sig-check/common",
  "src/noir/lib/sig-check/rsa",
  "src/noir/lib/sig-check/ecdsa",
  "src/noir/lib/sig-verify/rsa",
  "src/noir/lib/sig-verify/ecdsa",
  "src/noir/lib/hash-multiplex",
  "src/noir/lib/data-check/integrity",
  "src/noir/lib/data-check/expiry",
  "src/noir/lib/data-check/tbs-pubkey",
  "src/noir/lib/data-check/dg11",
  "src/noir/lib/compare/age",
  "src/noir/lib/compare/date",
  "src/noir/lib/disclose",
  "src/noir/lib/inclusion-check/country",
  "src/noir/lib/inclusion-check/place-of-birth",
  "src/noir/lib/exclusion-check/country",
  "src/noir/lib/exclusion-check/place-of-birth",
  "src/noir/lib/exclusion-check/sanctions",
  "src/noir/lib/bind",
]
